languageCode = "en-us"
title = "LUCKYHOLE"
baseURL = "https://effervescent-semifreddo-211237.netlify.app"
theme = "massively"
#googleanalytics = ""
#disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

[params]
  # set below parameter to define a favicon
  favicon = "images/luckyhole-removebg-preview.ico"
  # set to change date format
  # dateFormat = "2.1.2006"
  #backgroundPath = "images/luckyhole.jpg"

# Below parameters can be set to override default post settings
# [params.posts]
#     folderName = "post"
#     pageSize = "2"
#     featuredPost = true
#     paginationPages = 2
#     showFirstLast = false
 
[languages]
[languages.en]
  languageName = "English"
[languages.zh]
  languageName = "中文"
#[languages.es]
#  languageName = "Español"
#  title = "Massively - Versión Español"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"

